name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: raviqqe/enable-homebrew@main
      - run: brew install pen-lang/pen/pen
      - run: pen build
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: raviqqe/enable-homebrew@main
      - run: brew install pen-lang/pen/pen
      - run: pen test
  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: raviqqe/enable-homebrew@main
      - run: brew install pen-lang/pen/pen
      - run: pen format --check
  spell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@main
        with:
          files: "**/*.{md,pen,sh}"
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npx markdown-link-check README.md
